### ISSUE TITLE
Can't use Input method with autocomplete-plus

### ISSUE THREAD

**Issue by MiincGu** [atom-community/autocomplete-plus#210] opened 2015-01-29 09:06 UTC
When I use input method to enter some text in atom, input method will popup a window to let me choose which charactor to confirm. But after 100ms(autocomplete-plus default value), the autocomplete window popup, and it hide the input method window. So I just can't enter any word.

```
OS: Mac OS X 10.10.2
Atom: 0.176.0
Autocomplete-plus: 2.0.2
Input Method: Chinese Pinyin IME (Mac OS X preinstalled)
```

**Comment by joefitzgerald** [comment] 2015-01-29 17:02
@MiincGu I'm not sure I've ever entered text using the technique you described (because I only ever write English). Would it be possible to either capture a video / animated gif of this, or do a screen sharing session with us so we can observe it?

**Comment by MiincGu** [comment] 2015-01-29 23:49
Hi,
Here's the video. Hope it can help.

https://www.youtube.com/watch?v=eAY4W-soaII&feature=youtube_gdata_player

**Comment by park9140** [comment] 2015-02-02 16:28
I believe this is a duplicate of #200.

**Comment by joefitzgerald** [comment] 2015-02-02 16:29
Yes, it was opened while 200 was closed.

**Comment by chrisyip** [comment] 2015-02-04 09:04
I found out there's a [`compositionstart`](https://developer.mozilla.org/en-US/docs/Web/Events/compositionstart) API for detecting IME input status.

The order that input event fired:

1. keydown
- compositionstart
- input
- keyup
- compositionend
- change

Here is a [demo](http://plnkr.co/edit/ZwT94mgfarR9edrocPqg?p=preview), open console and try input something.

Though this order maybe different in real world, but `compositionstart` is always fired right after `keydown`. So maybe we can just detect if `compositionstart` is fired to determine if active `autocomplete-plus`.

I will go through `autocomplete-plus`'s source code and try to submit a PR in this weekend.

If someone is working on it, please leave a message.

**Comment by joefitzgerald** [comment] 2015-02-04 14:46
@chrisyip: please feel free to submit a PR to fix this. None of us have Google IME so it's a little hard for us to reproduce at this time. We do handle native IME correctly, and have a test confirming as such.

**Closed** 2015-02-06 16:01 UTC
Labels: bug
