### ISSUE TITLE
Comments causes Atom to hang.

### ISSUE THREAD

**Issue by baelter** [atom-community/autocomplete-plus#313] opened 2015-03-10 09:40 UTC
Toggling comments via editor:toggle-line-comments works fine but adding or removing comments manually hangs atom.

It is the compilation of suggestion list that hangs atom.
I can not reproduce in --safe.

I'm experiencing this in Atom 0.178.0 on Ubuntu 14.04.2 LTS 64-bit with Gnome 3.12.2.

Originally though this was a javascript file exclusive bug so started conversation about this here: https://github.com/atom/language-javascript/issues/26#issuecomment-77549578
but later found out that its not language specific. Tested with ruby files as well.

**Comment by joefitzgerald** [comment] 2015-03-10 13:15
Can you please update atom and autocomplete-plus and retest?

**Comment by joefitzgerald** [comment] 2015-03-17 16:58
I cannot reproduce this. As @benogle [mentioned in #315](https://github.com/atom-community/autocomplete-plus/issues/315#issuecomment-81964852):

> Do you guys ave any other autocomplete providers installed? Can you paste in `apm list` for me?
> 
> Pasting in the entire error report (you can copy via the clipboard icon in the red notification) would be helpful.

**Comment by joefitzgerald** [comment] 2015-03-17 17:01
Does this problem still exist, after upgrading to `v2.5.0`?

**Comment by joefitzgerald** [comment] 2015-03-31 22:54
@baelter I am closing this due to a lack of a response. Please respond back if you are still experiencing this issue.

**Closed by joefitzgerald** 2015-03-31 22:54 UTC
Labels: bug
