### ISSUE TITLE
Uncaught TypeError: undefined is not a function (persists)

### ISSUE THREAD

**Issue by sjamesmccarthy** [atom-community/autocomplete-plus#315] opened 2015-03-11 17:05 UTC
Atom v. 0.187.0
updated package, restarted.
uninstalled package, restarted.
installed packaged from terminal with APM (apm install autocomplete-plus) restarted.

Problem persists.
My screen gets bombarded with red warnings and need to uninstall permanently until a fix is provided I guess.

__Error Summary__
/Applications/Atom.app/Contents/Resources/app/node_modules/scoped-property-store/lib/scoped-property-store.js:240

__Stack Trace__
TypeError: undefined is not a function
  at ScopedPropertyStore.module.exports.ScopedPropertyStore.parseScopeChain (/Applications/Atom.app/Contents/Resources/app/node_modules/scoped-property-store/lib/scoped-property-store.js:240:31)
  at ScopedPropertyStore.module.exports.ScopedPropertyStore.getAll (/Applications/Atom.app/Contents/Resources/app/node_modules/scoped-property-store/lib/scoped-property-store.js:94:21)
  at ProviderManager.module.exports.ProviderManager.providersForScopeDescriptor (/Users/jimm/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:45:24)
  at ProviderManager.providersForScopeDescriptor (/Users/jimm/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/jimm/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:124:34)
  at AutocompleteManager.getSuggestionsFromProviders (/Users/jimm/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/jimm/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:121:6)
  at /Users/jimm/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

**Comment by sparkjames** [comment] 2015-03-11 18:44
Just to add to this, I usually only see this error when I start typing a comment with /*

It doesn't happen every time but it's like the plugin wants to autocomplete the comment but can't quite figure it out.

**Comment by filipeguelber** [comment] 2015-03-12 22:12
+1

**Comment by alexmagill** [comment] 2015-03-13 10:15
This problem is repeatable if you try and autocomplete (by typing  / ) with multiple selection points active. (for example, wrapping a bunch of items in opening and closing html list tags)

**Comment by benogle** [comment] 2015-03-16 22:17
I cant reproduce this. Do you guys ave any other autocomplete providers installed? Can you paste in `apm list` for me?

Pasting in the entire error report (you can copy via the clipboard icon in the red notification) would be helpful.

**Comment by benogle** [comment] 2015-03-16 23:12
Closing in favor of #308

**Closed by benogle** 2015-03-16 23:12 UTC
Labels: bug
