### ISSUE TITLE
Dropdown offset affected by minimap

### ISSUE THREAD

**Issue by lexicalunit** [atom-community/autocomplete-plus#412] opened 2015-04-22 20:19 UTC
```shell
$ atom --version
0.194.0

$ apm upgrade --confirm false
Package Updates Available (0)
└── (empty)

$ cd ~/.atom
$ find . -maxdepth 1 -type f -print -exec cat {} \;
./config.cson
"*":
  "exception-reporting":
    userId: "b80c92fe-cfc6-9384-b3e1-f9439e466aa7"
  welcome:
    showOnStartup: false
  core: {}
  editor:
    invisibles: {}
./init.coffee
./keymap.cson
./projects.cson
{}./styles.less

$ apm list -i
/Users/me/.atom/packages (2)
├── autocomplete-plus@2.12.0
└── minimap@4.7.6
```

![enable_offset](https://cloud.githubusercontent.com/assets/1903876/7284400/e2069b90-e902-11e4-9402-1e41bd25e8e6.png)

With minimap disabled I see this instead:

![disable_offset](https://cloud.githubusercontent.com/assets/1903876/7284402/e5c9f286-e902-11e4-9f59-3d657f55a8c0.png)

**Comment by lexicalunit** [comment] 2015-04-22 20:22
Oh, just found this issue in the minimap project: https://github.com/atom-minimap/minimap/issues/317

**Comment by joefitzgerald** [comment] 2015-04-22 20:26
Sorry you're having issues! Sounds like a core overlay issue, and related to / a duplicate of #394.

**Closed by joefitzgerald** 2015-04-22 20:26 UTC
