### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by adham90** [atom-community/autocomplete-plus#237] opened 2015-02-04 02:00 UTC
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:64:11)
ProviderManager.module.exports.ProviderManager.consumeApi (/home/adham/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:110:28)
```

**Comment by joefitzgerald** [comment] 2015-02-04 02:04
This is fixed. Please update. Duplicate of #234, #229.

**Closed by joefitzgerald** 2015-02-04 02:04 UTC
