### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeChains' of undefined

### ISSUE THREAD

**Issue by joefitzgerald** [atom-community/autocomplete-plus#404] opened 2015-04-19 07:11 UTC
There is an issue with the symbol-store where deleted files cause a persistent and very reproducible error until atom is reloaded.

1. Open a file that contains text with some grammar that is not blacklisted by your autocomplete-plus config
2. Delete the file
3. Open some other file that still exists, which contains text
4. Type a character (that triggers a suggestion request)
5. Observe the following error

Additional detail:

![screen shot 2015-04-19 at 5 05 21 pm](https://cloud.githubusercontent.com/assets/744740/7218509/1710a90a-e6b7-11e4-9929-97e5292b967f.png)

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.11.0

### Stack Trace

Uncaught TypeError: Cannot read property 'scopeChains' of undefined

```
At /Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/symbol-store.coffee:94

TypeError: Cannot read property 'scopeChains' of undefined
  at Symbol.appliesToConfig (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/symbol-store.coffee:94:24)
  at SymbolStore.module.exports.SymbolStore.symbolsForConfig (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/symbol-store.coffee:131:38)
  at SymbolProvider.module.exports.SymbolProvider.findSuggestionsForWord (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/symbol-provider.coffee:184:31)
  at SymbolProvider.findSuggestionsForWord (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/symbol-provider.coffee:3:1)
  at SymbolProvider.module.exports.SymbolProvider.getSuggestions (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/symbol-provider.coffee:176:6)
  at SymbolProvider.getSuggestions (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/symbol-provider.coffee:3:1)
  at /Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:152:45
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:135:15)
  at AutocompleteManager.getSuggestionsFromProviders (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:129:6)
  at /Users/jfitzgerald/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1

```

### Commands

```
  5x -0:28.1 core:backspace (atom-text-editor.editor.mini)
     -0:23.5 core:confirm (atom-text-editor.editor.mini)
     -0:20.1 editor:newline (atom-text-editor.editor)
     -0:19.6 core:save (atom-text-editor.editor)
     -0:01.1 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "markdown-format"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "autocomplete-plus": {
    "includeCompletionsFromAllBuffers": true,
    "strictMatching": true,
    "defaultProvider": "Symbol",
    "suggestionListFollows": "Word"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.11.0
autocomplete-snippets, v1.2.0
go-plus, v3.3.6
language-asciidoc, v0.11.1
language-docker, v1.1.3
language-tcl, v0.1.0
linter, v0.12.0
linter-coffeelint, v0.2.1
markdown-table-formatter, v2.5.2
pretty-json, v0.3.3
tabs-to-spaces, v0.9.2

# Dev
autocomplete-paths, v1.0.2
autocomplete-plus, v2.11.0
autocomplete-snippets, v1.2.0
go-plus, v3.3.6
```

**Comment by joefitzgerald** [comment] 2015-04-20 17:54
@benogle was this enough for a repro on your end?

**Comment by benogle** [comment] 2015-04-20 17:54
Not sure. I wont be able to get to this for a couple hours

**Comment by benogle** [comment] 2015-04-20 22:34
> Delete the file

Do you mean delete it from disk? Are you deleting it from disk when the file is open? Or did you close it first? Do you see the same thing when you just close the file? 

Does this happen on current master? I am unable to reproduce.

There was an issue in [this code](https://github.com/atom-community/autocomplete-plus/blob/266aca1af4d0daa9e0ffd6b27e3aa4a99ed72966/lib/symbol-store.coffee#L30) generating a similar error. I was setting `@metadataByPath[bufferPath]` to undefined. Having a key point to undefined would cause this error by executing the loop code against undefined.

**Comment by joefitzgerald** [comment] 2015-04-20 22:42
> Do you mean delete it from disk?

I mean right click on the file in the tree-view, and select 'delete' (which sends it to Trash). The file is open when I do this. Atom leaves the file open, even when it resides in Trash.

> Does this happen on current master?

Yes.

**Comment by joefitzgerald** [comment] 2015-04-20 22:44
![screen shot 2015-04-19 at 5 05 21 pm](https://cloud.githubusercontent.com/assets/744740/7218509/1710a90a-e6b7-11e4-9929-97e5292b967f.png)

This shows the state of @metadataByPath when i have opened `go-runtime-view-spec.coffee`, then deleted it via the tree view, and kept the file open.

**Closed** 2015-04-20 23:33 UTC
Labels: needs to be reproduced
