### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('IEnumerable<IGrouping<TKey, char>>') contains HTML space characters, which are not valid in tokens.

### ISSUE THREAD

**Issue by ctolkien** [atom-community/autocomplete-plus#413] opened 2015-04-23 08:52 UTC
To Repo, have a `type` that has a space in the name.

**Atom Version**: 0.194.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [autocomplete-plus](https://github.com/atom-community/autocomplete-plus) package, v2.12.0

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('IEnumerable<IGrouping<TKey, char>>') contains HTML space characters, which are not valid in tokens.

```
At C:\Users\Chad Tolkien\.atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:229

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('IEnumerable<IGrouping<TKey, char>>') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at autocomplete-suggestion-list.SuggestionListElement.renderItem (C:\Users\Chad Tolkien\.atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:229:26)
  at autocomplete-suggestion-list.SuggestionListElement.renderItems (C:\Users\Chad Tolkien\.atom\packages\autocomplete-plus\lib\suggestion-list-element.coffee:169:6)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (c:\Users\Chad Tolkien\AppData\Local\atom\app-0.194.0\resources\app.asar\src\view-registry.js:168:9)
  at __bind (c:\Users\Chad Tolkien\AppData\Local\atom\app-0.194.0\resources\app.asar\src\view-registry.js:3:61)

```

### Commands

```
     -0:59.3.0 omnisharp-atom:toggle (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:52.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "autocomplete-plus-async",
      "language-objective-c"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "autocomplete-plus": {
    "defaultProvider": "Symbol",
    "builtinProviderBlacklist": ".source.cs",
    "confirmCompletion": "tab and enter"
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v3.0.4
autocomplete-plus, v2.12.0
linter, v0.12.1
omnisharp-atom, v0.3.0
react, v0.11.5

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment] 2015-04-23 23:21
Duplicate of #353.

**Closed by joefitzgerald** 2015-04-23 23:21 UTC
Labels: duplicate

**Comment by joefitzgerald** [comment] 2015-04-23 23:23
@ctolkien You should use IEnumerable<IGrouping<TKey, char>> as the `leftLabel` and `method` as the `type`.

**Comment by ctolkien** [comment] 2015-04-24 00:09
Ah, so "type" is not the return type, but the "type" of call.

**Comment by joefitzgerald** [comment] 2015-04-24 00:23
Yep, it is the type/kind/categorization of the suggestion itself (i.e. you might be suggesting a method that has a return type. The `text` might be `ToString()`, the `leftLabel` would be `string`, the `type` would be `method`.

Similarly, if someone has defined a variable: `var theString = "hello, world"`, and then subsequently tries to use it and types `theS`, you might have a suggestion which has `text` of `theString`, `leftLabel` of `System.String` (or `String`), `type` of `variable`, and `replacementPrefix` of `theS`.
