### ISSUE TITLE
ß seen as word limiter

### ISSUE THREAD

**Issue by I3ck** [atom-community/autocomplete-plus#203] opened 2015-01-26 13:24 UTC
When writing in german, words containing ß won't be seen as actual words.  
"Fußball" would create two new autocompletes (Fu and ball) instead of "Fußball".  
I assume this is the case for many other special characters, although I haven't tested that. (ß, ä, ö, ü, ...)

**Comment by joefitzgerald** [comment] 2015-01-26 13:42
Duplicate of #76.

**Closed by joefitzgerald** 2015-01-26 13:42 UTC
Labels: duplicate
