### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by alivelee** [atom-community/autocomplete-plus#239] opened 2015-02-04 08:21 UTC
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
ProviderManager.module.exports.ProviderManager.consumeApi (/Users/reddylee/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:110:28)
```

**Comment by steelbrain** [comment] 2015-02-04 11:51
Dupe of #238

**Comment by joefitzgerald** [comment] 2015-02-04 13:06
This is already fixed. Please update.

**Closed by joefitzgerald** 2015-02-04 13:06 UTC
