### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by alex** [atom-community/autocomplete-plus#234] opened 2015-02-04 00:04 UTC
atom.services is no longer available. To register service providers and
consumers, use the `providedServices` and `consumedServices` fields in
your package's package.json.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:64:11)
ProviderManager.module.exports.ProviderManager.consumeApi (/Users/alex_gaynor/.atom/packages/autocomplete-plus/lib/provider-manager.coffee:110:28)
```

**Comment by joefitzgerald** [comment] 2015-02-04 02:05
This is fixed. Please update. Duplicate of #229.

**Closed by joefitzgerald** 2015-02-04 02:05 UTC
