### ISSUE TITLE
Workspace.getEditors is deprecated.

### ISSUE THREAD

**Issue by Hokutosei** [atom-community/autocomplete-plus#361] opened 2015-04-07 01:22 UTC
Use Workspace::getTextEditors instead
```
Workspace.getEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:368:7)
FuzzyProvider.module.exports.FuzzyProvider.buildWordList (/Users/soliva/.atom/packages/autocomplete-plus/lib/fuzzy-provider.coffee:141:31)
```

used the utility in atom, from deprecation cop.

**Comment by joefitzgerald** [comment] 2015-04-08 06:04
Already fixed, in f8cac61. Duplicate of #350. Please update your version of autocomplete-plus and ensure you are running the latest version of atom.

**Closed by joefitzgerald** 2015-04-08 06:04 UTC
Labels: duplicate, invalid
