### ISSUE TITLE
autoActivationDelay is taking empty value automatically

### ISSUE THREAD

**Issue by fillipeamorim** [atom-community/autocomplete-plus#402] opened 2015-04-18 18:47 UTC
Even setting this to 100 milliseconds, when I return to the preferences, is empty again!

**Comment by benogle** [comment] 2015-04-20 22:44
Where are you setting this? In config file or in settings? 100 is the default, so it may be unsetting it back to the default. Can you set it to something other than 100?

**Comment by fillipeamorim** [comment] 2015-04-20 22:53
Hello. I tried setting in two ways, by the preferences screen plugin and directly in my configuration file, where the Atom puts the line.

In both attempts, tried to put the default value and other values and yet the field again becomes empty. When I open the preferences to view, the field is empty.

I uninstalled and installed again and the error persists!

**Comment by joefitzgerald** [comment] 2015-04-20 23:04
@fillipeamorim what version of Atom and autocomplete-plus are you using? I cannot reproduce this, and I can successfully set a different value for this configuration key via both preferences and the config. Closing / reopening each results in the value persisting.

![screen shot 2015-04-20 at 5 02 50 pm](https://cloud.githubusercontent.com/assets/744740/7242390/39e2262a-e77f-11e4-8bf1-8c4d116afe82.png)
![screen shot 2015-04-20 at 5 02 25 pm](https://cloud.githubusercontent.com/assets/744740/7242389/39e0102e-e77f-11e4-9baf-8b4f3bc325ae.png)

**Comment by fillipeamorim** [comment] 2015-04-22 19:31
The problem stopped happening here!

Sorry for the inconvenience!

**Closed** 2015-04-22 19:32 UTC
Labels: waiting for response
