### ISSUE TITLE
Autocomplete not completing but appending w/ suggestion - Ver 1.1.0 - Mac 10.10

### ISSUE THREAD

**Issue by tetriscode** [atom-community/autocomplete-plus#204] opened 2015-01-26 15:51 UTC
When I type 'ret', 'return' gets suggested. I then hit tab to confirm and 'retreturn' gets printed.

**Comment by joefitzgerald** [comment] 2015-01-26 16:18
Duplicate of #197, #188. Please check again when `autocomplete+` v2.0.0 is released, which should be in the next 24 hours.

**Closed by joefitzgerald** 2015-01-26 16:18 UTC
Labels: duplicate
